package com.app.coguardapp;

public class WebSiteContent {

    public String getWeb_site_content() {
        return web_site_content;
    }

    public void setWeb_site_content(String web_site_content) {
        this.web_site_content = web_site_content;
    }

    String web_site_content = "<div class=\"cb-meta\">\n" +
            "<h2 class=\"cb-post-title\"><a href=\"https://teyit.org/kayseri-belediyesinin-coffin-dance-ekibinin-fotografiyla-evdekal-cagrisi-yaptigi-iddiasi/\">Kayseri Belediyesi&#8217;nin Coffin Dance ekibinin fotoğrafıyla #EvdeKal çağrısı yaptığı iddiası</a></h2>\n" +
            "<div class=\"cb-byline\"><span class=\"cb-author\"> <a href=\"https://teyit.org/author/iremuludag/\">İrem Uludağ</a></span><span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span><span class=\"cb-date test\"><time datetime=\"2020-04-08\">08/04/2020<span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span>17:17</time></span></div>\n" +
            "<div class=\"cb-excerpt\">Kayseri Büyükşehir Belediyesi'nin vatandaşlarına Coffin Dance ekibinin fotoğrafı ile #EvdeKal çağrısı yaptığı iddia edildi. Ancak fotoğraf montajlanmış. </div>\n" +
            "<div class=\"cb-post-meta\"><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/analiz/\" title=\"Analiz tarafından eklenmiş tüm yazılar\">Analiz</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/saglik/\" title=\"Sağlık tarafından eklenmiş tüm yazılar\">Sağlık</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/yasam/\" title=\"Yaşam tarafından eklenmiş tüm yazılar\">Yaşam</a></span><span class=\"cb-comments cb-element\"><a href=\"https://teyit.org/kayseri-belediyesinin-coffin-dance-ekibinin-fotografiyla-evdekal-cagrisi-yaptigi-iddiasi/#respond\">Yorum yok</a></span></div>\n" +
            "</div>\n" +
            "</article>\n" +
            "<article id=\"post-35233\" class=\"cb-blog-style-b cb-bs-c cb-module-a cb-article cb-article-row-3 cb-article-row cb-img-above-meta clearfix cb-separated cb-no-2 post-35233 post type-post status-publish format-standard has-post-thumbnail hentry category-teyitpedia category-kriz tag-haber-tuketimi tag-koronavirus\">\n" +
            "<div class=\"cb-mask cb-img-fw\" style=\"background-color: #222;\">\n" +
            "<a href=\"https://teyit.org/koronavirus-salgininda-haber-tuketimi-ve-ipuclari/\"><img width=\"360\" height=\"240\" src=\"https://teyit.fra1.cdn.digitaloceanspaces.com/wp-content/uploads/2020/04/koronavirus-salgininda-haber-tuketimi-ve-ipuclari-360x240.png\" class=\"attachment-cb-360-240 size-cb-360-240 wp-post-image\" alt=\"\" /></a> </div>\n" +
            "<div class=\"cb-meta\">\n" +
            "<h2 class=\"cb-post-title\"><a href=\"https://teyit.org/koronavirus-salgininda-haber-tuketimi-ve-ipuclari/\">Koronavirüs salgınında haber tüketimi ve ipuçları</a></h2>\n" +
            "<div class=\"cb-byline\"><span class=\"cb-date test\"><time datetime=\"2020-04-08\">08/04/2020<span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span>17:14</time></span></div>\n" +
            "<div class=\"cb-excerpt\">Bu rehber, haber kaynaklarının hangisinin sizin için, size uygun olduğuna karar vermenize yardımcı olacak.</div>\n" +
            "<div class=\"cb-post-meta\"><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/teyitpedia/\" title=\"#teyitpedia tarafından eklenmiş tüm yazılar\">#teyitpedia</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/kriz/\" title=\"Kriz tarafından eklenmiş tüm yazılar\">Kriz</a></span><span class=\"cb-comments cb-element\"><a href=\"https://teyit.org/koronavirus-salgininda-haber-tuketimi-ve-ipuclari/#respond\">Yorum yok</a></span></div>\n" +
            "</div>\n" +
            "</article>\n" +
            "<article id=\"post-35200\" class=\"cb-blog-style-b cb-bs-c cb-module-a cb-article cb-article-row-3 cb-article-row cb-img-above-meta clearfix cb-separated cb-no-3 post-35200 post type-post status-publish format-standard has-post-thumbnail hentry category-analiz category-bilim-teknoloji category-kriz category-saglik category-yanlis tag-5g tag-cin tag-komplo-teorileri tag-koronavirus tag-whatsapp\">\n" +
            "<div class=\"cb-mask cb-img-fw\" style=\"background-color: #222;\">\n" +
            "<a href=\"https://teyit.org/5g-whatsapp-mesaji-i-5g-protestosunu-gosterdigi-iddia-edilen-videolar-baska-olaylardan/\"><img width=\"360\" height=\"240\" src=\"https://teyit.fra1.cdn.digitaloceanspaces.com/wp-content/uploads/2020/04/5G-WhatsApp-mesaji-zinciri-5G-protestosunu-gosterdigi-iddia-edilen-videolar-baska-olaylardan-360x240.png\" class=\"attachment-cb-360-240 size-cb-360-240 wp-post-image\" alt=\"\" /></a> </div>\n" +
            "<div class=\"cb-meta\">\n" +
            "<h2 class=\"cb-post-title\"><a href=\"https://teyit.org/5g-whatsapp-mesaji-i-5g-protestosunu-gosterdigi-iddia-edilen-videolar-baska-olaylardan/\">5G WhatsApp mesajı I: 5G protestosunu gösterdiği iddia edilen videolar başka olaylardan</a></h2>\n" +
            "<div class=\"cb-byline\"><span class=\"cb-author\"> <a href=\"https://teyit.org/author/ezgi/\">Ezgi Toprak</a></span><span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span><span class=\"cb-date test\"><time datetime=\"2020-04-08\">08/04/2020<span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span>12:01</time></span></div>\n" +
            "<div class=\"cb-excerpt\">Covid-19 hayatımıza girdiğinden bu yana, virüsün nasıl ortaya çıktığı da merak ediliyor. Bu kez salgının 5G teknolojisiyle bir bağı olduğu konusu gündemde. İlk bölümde WhatsApp üzerinden gelen bir mesajda bulunan videoları inceliyoruz.</div>\n" +
            "<div class=\"cb-post-meta\"><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/analiz/\" title=\"Analiz tarafından eklenmiş tüm yazılar\">Analiz</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/bilim-teknoloji/\" title=\"Bilim - Teknoloji tarafından eklenmiş tüm yazılar\">Bilim - Teknoloji</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/kriz/\" title=\"Kriz tarafından eklenmiş tüm yazılar\">Kriz</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/saglik/\" title=\"Sağlık tarafından eklenmiş tüm yazılar\">Sağlık</a></span><span class=\"cb-comments cb-element\"><a href=\"https://teyit.org/5g-whatsapp-mesaji-i-5g-protestosunu-gosterdigi-iddia-edilen-videolar-baska-olaylardan/#respond\">Yorum yok</a></span></div>\n" +
            "</div>\n" +
            "</article>\n" +
            "<article id=\"post-35180\" class=\"cb-blog-style-b cb-bs-c cb-module-a cb-article cb-article-row-3 cb-article-row cb-img-above-meta clearfix cb-separated cb-no-1 post-35180 post type-post status-publish format-standard has-post-thumbnail hentry category-analiz category-kriz category-saglik category-yanlis tag-karantina tag-konya tag-koronavirus tag-umre tag-yurt-odalari\">\n" +
            "<div class=\"cb-mask cb-img-fw\" style=\"background-color: #222;\">\n" +
            "<a href=\"https://teyit.org/fotograflarin-umreden-donenlerin-kaldigi-yurt-odalarinin-son-halini-gosterdigi-iddiasi/\"><img width=\"360\" height=\"240\" src=\"https://teyit.fra1.cdn.digitaloceanspaces.com/wp-content/uploads/2020/04/Fotografların-umreden-donenlerin-kaldıgı-yurt-odalarının-son-halini-gosterdigi-iddiası-360x240.png\" class=\"attachment-cb-360-240 size-cb-360-240 wp-post-image\" alt=\"\" /></a> </div>\n" +
            "<div class=\"cb-meta\">\n" +
            "<h2 class=\"cb-post-title\"><a href=\"https://teyit.org/fotograflarin-umreden-donenlerin-kaldigi-yurt-odalarinin-son-halini-gosterdigi-iddiasi/\">Fotoğrafların umreden dönenlerin kaldığı yurt odalarının son halini gösterdiği iddiası</a></h2>\n" +
            "<div class=\"cb-byline\"><span class=\"cb-author\"> <a href=\"https://teyit.org/author/iremuludag/\">İrem Uludağ</a></span><span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span><span class=\"cb-date test\"><time datetime=\"2020-04-08\">08/04/2020<span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span>08:47</time></span></div>\n" +
            "<div class=\"cb-excerpt\">Fotoğrafın, umreden dönen vatandaşların karantina sonrası kaldığı yurt odasının son halini gösterdiği iddia edildi. Ancak fotoğraf Haziran ayında paylaşılmış. </div>\n" +
            "<div class=\"cb-post-meta\"><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/analiz/\" title=\"Analiz tarafından eklenmiş tüm yazılar\">Analiz</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/kriz/\" title=\"Kriz tarafından eklenmiş tüm yazılar\">Kriz</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/saglik/\" title=\"Sağlık tarafından eklenmiş tüm yazılar\">Sağlık</a></span><span class=\"cb-comments cb-element\"><a href=\"https://teyit.org/fotograflarin-umreden-donenlerin-kaldigi-yurt-odalarinin-son-halini-gosterdigi-iddiasi/#comments\">4 yorum</a></span></div>\n" +
            "</div>\n" +
            "</article>\n" +
            "<article id=\"post-35167\" class=\"cb-blog-style-b cb-bs-c cb-module-a cb-article cb-article-row-3 cb-article-row cb-img-above-meta clearfix cb-separated cb-no-2 post-35167 post type-post status-publish format-standard has-post-thumbnail hentry category-teyitpedia tag-ogretmen tag-uzaktan-egitim tag-zoom\">\n" +
            "<div class=\"cb-mask cb-img-fw\" style=\"background-color: #222;\">\n" +
            "<a href=\"https://teyit.org/tartismalarin-merkezindeki-program-zoom-guvenli-mi/\"><img width=\"360\" height=\"240\" src=\"https://teyit.fra1.cdn.digitaloceanspaces.com/wp-content/uploads/2020/04/tartismalarin-merkezindeki-program-zoom-guvenli-mi-360x240.png\" class=\"attachment-cb-360-240 size-cb-360-240 wp-post-image\" alt=\"\" /></a> </div>\n" +
            "<div class=\"cb-meta\">\n" +
            "<h2 class=\"cb-post-title\"><a href=\"https://teyit.org/tartismalarin-merkezindeki-program-zoom-guvenli-mi/\">Tartışmaların merkezindeki program Zoom güvenli mi?</a></h2>\n" +
            "<div class=\"cb-byline\"><span class=\"cb-author\"> <a href=\"https://teyit.org/author/emre/\">Emre Saklıca</a></span><span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span><span class=\"cb-date test\"><time datetime=\"2020-04-07\">07/04/2020<span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span>18:37</time></span></div>\n" +
            "<div class=\"cb-excerpt\">Uzaktan eğitimin başlamasıyla tartışmaların odağı noktasına gelen Zoom programı ne kadar güvenli? Kişisel güvenliğimizi korumak için neler yapabiliriz?</div>\n" +
            "<div class=\"cb-post-meta\"><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/teyitpedia/\" title=\"#teyitpedia tarafından eklenmiş tüm yazılar\">#teyitpedia</a></span><span class=\"cb-comments cb-element\"><a href=\"https://teyit.org/tartismalarin-merkezindeki-program-zoom-guvenli-mi/#comments\">2 yorum</a></span></div>\n" +
            "</div>\n" +
            "</article>\n" +
            "<article id=\"post-35134\" class=\"cb-blog-style-b cb-bs-c cb-module-a cb-article cb-article-row-3 cb-article-row cb-img-above-meta clearfix cb-separated cb-no-3 post-35134 post type-post status-publish format-standard has-post-thumbnail hentry category-analiz category-kriz category-saglik category-yanlis tag-covid-19 tag-italya tag-koronavirus tag-venezuela\">\n" +
            "<div class=\"cb-mask cb-img-fw\" style=\"background-color: #222;\">\n" +
            "<a href=\"https://teyit.org/ailesini-covid-19dan-kaybeden-italyan-milyarderin-parasini-sokaga-sactigi-iddiasi/\"><img width=\"360\" height=\"240\" src=\"https://teyit.fra1.cdn.digitaloceanspaces.com/wp-content/uploads/2020/04/Adsız-tasarım-360x240.png\" class=\"attachment-cb-360-240 size-cb-360-240 wp-post-image\" alt=\"\" /></a> </div>\n" +
            "<div class=\"cb-meta\">\n" +
            "<h2 class=\"cb-post-title\"><a href=\"https://teyit.org/ailesini-covid-19dan-kaybeden-italyan-milyarderin-parasini-sokaga-sactigi-iddiasi/\">Ailesini Covid-19’dan kaybeden İtalyan milyarderin parasını sokağa saçtığı iddiası</a></h2>\n" +
            "<div class=\"cb-byline\"><span class=\"cb-author\"> <a href=\"https://teyit.org/author/secil/\">Seçil Türkkan</a></span><span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span><span class=\"cb-date test\"><time datetime=\"2020-04-06\">06/04/2020<span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span>17:50</time></span></div>\n" +
            "<div class=\"cb-excerpt\">İtalya'da bir milyonerin ailesini Covid-19 nedeniyle kaybettiği için servetini sokaklara saçtığı iddia edildi. Ancak iddiaya ait fotoğraflar Venezuela'daki bir banka soygunundan. </div>\n" +
            "<div class=\"cb-post-meta\"><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/analiz/\" title=\"Analiz tarafından eklenmiş tüm yazılar\">Analiz</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/kriz/\" title=\"Kriz tarafından eklenmiş tüm yazılar\">Kriz</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/saglik/\" title=\"Sağlık tarafından eklenmiş tüm yazılar\">Sağlık</a></span><span class=\"cb-comments cb-element\"><a href=\"https://teyit.org/ailesini-covid-19dan-kaybeden-italyan-milyarderin-parasini-sokaga-sactigi-iddiasi/#comments\">2 yorum</a></span></div>\n" +
            "</div>\n" +
            "</article>\n" +
            "<article id=\"post-35090\" class=\"cb-blog-style-b cb-bs-c cb-module-a cb-article cb-article-row-3 cb-article-row cb-img-above-meta clearfix cb-separated cb-no-1 post-35090 post type-post status-publish format-standard has-post-thumbnail hentry category-analiz category-kriz category-saglik category-yanlis tag-alabama tag-covid-19 tag-koronavirus\">\n" +
            "<div class=\"cb-mask cb-img-fw\" style=\"background-color: #222;\">\n" +
            "<a href=\"https://teyit.org/fotograf-covid-19-nedeniyle-vefat-eden-babanin-cocuguyla-son-gorusmesini-gostermiyor/\"><img width=\"360\" height=\"240\" src=\"https://teyit.fra1.cdn.digitaloceanspaces.com/wp-content/uploads/2020/04/fotograf-covid-19-nedeniyle-vefat-edenin-babanin-cocuguyla-son-gorusmesini-gostermiyor-360x240.png\" class=\"attachment-cb-360-240 size-cb-360-240 wp-post-image\" alt=\"\" /></a> </div>\n" +
            "<div class=\"cb-meta\">\n" +
            "<h2 class=\"cb-post-title\"><a href=\"https://teyit.org/fotograf-covid-19-nedeniyle-vefat-eden-babanin-cocuguyla-son-gorusmesini-gostermiyor/\">Fotoğraf Covid-19 nedeniyle vefat eden babanın çocuğuyla son görüşmesini göstermiyor</a></h2>\n" +
            "<div class=\"cb-byline\"><span class=\"cb-author\"> <a href=\"https://teyit.org/author/emre/\">Emre Saklıca</a></span><span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span><span class=\"cb-date test\"><time datetime=\"2020-04-05\">05/04/2020<span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span>22:25</time></span></div>\n" +
            "<div class=\"cb-excerpt\">Sosyal medyada yaygınlaşan fotoğrafın Covid-19 nedeniyle yaşamını yitiren Seyfi Al Cherkesi'nin, ölmeden önce oğlunu son görüşünü gösterdiği iddia edildi. Ancak iddia doğru değil.</div>\n" +
            "<div class=\"cb-post-meta\"><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/analiz/\" title=\"Analiz tarafından eklenmiş tüm yazılar\">Analiz</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/kriz/\" title=\"Kriz tarafından eklenmiş tüm yazılar\">Kriz</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/saglik/\" title=\"Sağlık tarafından eklenmiş tüm yazılar\">Sağlık</a></span><span class=\"cb-comments cb-element\"><a href=\"https://teyit.org/fotograf-covid-19-nedeniyle-vefat-eden-babanin-cocuguyla-son-gorusmesini-gostermiyor/#comments\">2 yorum</a></span></div>\n" +
            "</div>\n" +
            "</article>\n" +
            "<article id=\"post-35036\" class=\"cb-blog-style-b cb-bs-c cb-module-a cb-article cb-article-row-3 cb-article-row cb-img-above-meta clearfix cb-separated cb-no-2 post-35036 post type-post status-publish format-standard has-post-thumbnail hentry category-icgoru tag-kaynak-kullanimi tag-teyit-link\">\n" +
            "<div class=\"cb-mask cb-img-fw\" style=\"background-color: #222;\">\n" +
            "<a href=\"https://teyit.org/gulumseyin-linklendiniz/\"><img width=\"360\" height=\"240\" src=\"https://teyit.fra1.cdn.digitaloceanspaces.com/wp-content/uploads/2020/04/Gülümseyin-Linklendiniz-360x240.png\" class=\"attachment-cb-360-240 size-cb-360-240 wp-post-image\" alt=\"\" /></a> </div>\n" +
            "<div class=\"cb-meta\">\n" +
            "<h2 class=\"cb-post-title\"><a href=\"https://teyit.org/gulumseyin-linklendiniz/\">Gülümseyin linklendiniz!</a></h2>\n" +
            "<div class=\"cb-byline\"><span class=\"cb-author\"> <a href=\"https://teyit.org/author/secil/\">Seçil Türkkan</a></span><span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span><span class=\"cb-date test\"><time datetime=\"2020-04-04\">04/04/2020<span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span>16:41</time></span></div>\n" +
            "<div class=\"cb-excerpt\">Teyit'te kullandığımız kaynaklarımızı paylaşma yöntemi, bizi birbirimize bağlıyor ve bilgiyi özgürleştiriyor.</div>\n" +
            "<div class=\"cb-post-meta\"><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/icgoru/\" title=\"İçgörü tarafından eklenmiş tüm yazılar\">İçgörü</a></span><span class=\"cb-comments cb-element\"><a href=\"https://teyit.org/gulumseyin-linklendiniz/#comments\">1 Yorum</a></span></div>\n" +
            "</div>\n" +
            "</article>\n" +
            "<article id=\"post-35048\" class=\"cb-blog-style-b cb-bs-c cb-module-a cb-article cb-article-row-3 cb-article-row cb-img-above-meta clearfix cb-separated cb-no-3 post-35048 post type-post status-publish format-standard has-post-thumbnail hentry category-buyutec category-dosya category-kriz category-politika category-saglik tag-covid-19 tag-devlet-bahceli tag-donald-trump tag-koronavirus tag-trafik-kazalari\">\n" +
            "<div class=\"cb-mask cb-img-fw\" style=\"background-color: #222;\">\n" +
            "<a href=\"https://teyit.org/buyutec-salgin-trafik-kazalariyla-karsilastirilabilir-mi/\"><img width=\"360\" height=\"240\" src=\"https://teyit.fra1.cdn.digitaloceanspaces.com/wp-content/uploads/2020/04/buyutec-salgin-trafik-kazalariyla-karsilastirilabilir-mi-360x240.png\" class=\"attachment-cb-360-240 size-cb-360-240 wp-post-image\" alt=\"\" /></a> </div>\n" +
            "<div class=\"cb-meta\">\n" +
            "<h2 class=\"cb-post-title\"><a href=\"https://teyit.org/buyutec-salgin-trafik-kazalariyla-karsilastirilabilir-mi/\">Büyüteç: Salgın trafik kazalarıyla karşılaştırılabilir mi?</a></h2>\n" +
            "<div class=\"cb-byline\"><span class=\"cb-author\"> <a href=\"https://teyit.org/author/ezgi/\">Ezgi Toprak</a></span><span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span><span class=\"cb-date test\"><time datetime=\"2020-04-04\">04/04/2020<span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span>16:31</time></span></div>\n" +
            "<div class=\"cb-excerpt\">Salgınlar ve trafik kazaları karşılaştırılabilir mi? Konuyu, büyüteç yazımızda inceledik. </div>\n" +
            "<div class=\"cb-post-meta\"><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/dosya/buyutec/\" title=\"Büyüteç tarafından eklenmiş tüm yazılar\">Büyüteç</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/dosya/\" title=\"Dosya tarafından eklenmiş tüm yazılar\">Dosya</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/kriz/\" title=\"Kriz tarafından eklenmiş tüm yazılar\">Kriz</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/politika/\" title=\"Politika tarafından eklenmiş tüm yazılar\">Politika</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/saglik/\" title=\"Sağlık tarafından eklenmiş tüm yazılar\">Sağlık</a></span><span class=\"cb-comments cb-element\"><a href=\"https://teyit.org/buyutec-salgin-trafik-kazalariyla-karsilastirilabilir-mi/#comments\">1 Yorum</a></span></div>\n" +
            "</div>\n" +
            "</article>\n" +
            "<article id=\"post-35059\" class=\"cb-blog-style-b cb-bs-c cb-module-a cb-article cb-article-row-3 cb-article-row cb-img-above-meta clearfix cb-separated cb-no-1 post-35059 post type-post status-publish format-standard has-post-thumbnail hentry category-teyitpedia tag-bot tag-botlar tag-twitter tag-yanlis-bilgi\">\n" +
            "<div class=\"cb-mask cb-img-fw\" style=\"background-color: #222;\">\n" +
            "<a href=\"https://teyit.org/arastirma-twitterda-koronavirus-endisesi-yaratanlar-botlar-olabilir/\"><img width=\"360\" height=\"240\" src=\"https://teyit.fra1.cdn.digitaloceanspaces.com/wp-content/uploads/2020/04/arastirma-twitterda-koronavirus-endisesi-yaratanlar-botlar-olabilir-360x240.png\" class=\"attachment-cb-360-240 size-cb-360-240 wp-post-image\" alt=\"\" /></a> </div>\n" +
            "<div class=\"cb-meta\">\n" +
            "<h2 class=\"cb-post-title\"><a href=\"https://teyit.org/arastirma-twitterda-koronavirus-endisesi-yaratanlar-botlar-olabilir/\">Araştırma: Twitter&#8217;da koronavirüs endişesi yaratanlar bot olabilir</a></h2>\n" +
            "<div class=\"cb-byline\"><span class=\"cb-date test\"><time datetime=\"2020-04-04\">04/04/2020<span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span>15:49</time></span></div>\n" +
            "<div class=\"cb-excerpt\">‘Sara,’ ‘Sharon,’ ve ‘Mel’ ile tanışın. Twitter’da koronavirüs endişesi yaratanlar bot olabilir.</div>\n" +
            "<div class=\"cb-post-meta\"><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/teyitpedia/\" title=\"#teyitpedia tarafından eklenmiş tüm yazılar\">#teyitpedia</a></span><span class=\"cb-comments cb-element\"><a href=\"https://teyit.org/arastirma-twitterda-koronavirus-endisesi-yaratanlar-botlar-olabilir/#respond\">Yorum yok</a></span></div>\n" +
            "</div>\n" +
            "</article>\n" +
            "<article id=\"post-35046\" class=\"cb-blog-style-b cb-bs-c cb-module-a cb-article cb-article-row-3 cb-article-row cb-img-above-meta clearfix cb-separated cb-no-2 post-35046 post type-post status-publish format-standard has-post-thumbnail hentry category-video tag-bulten tag-covid tag-koronavirus tag-teyit\">\n" +
            "<div class=\"cb-mask cb-img-fw\" style=\"background-color: #222;\">\n" +
            "<a href=\"https://teyit.org/video-covid-19-postasi-1-bolum/\"><img width=\"360\" height=\"240\" src=\"https://teyit.fra1.cdn.digitaloceanspaces.com/wp-content/uploads/2020/04/Thumbnail_Site-360x240.png\" class=\"attachment-cb-360-240 size-cb-360-240 wp-post-image\" alt=\"\" /></a> </div>\n" +
            "<div class=\"cb-meta\">\n" +
            "<h2 class=\"cb-post-title\"><a href=\"https://teyit.org/video-covid-19-postasi-1-bolum/\">Video: Covid-19 Postası &#8211; 1. Bölüm</a></h2>\n" +
            "<div class=\"cb-byline\"><span class=\"cb-date test\"><time datetime=\"2020-04-04\">04/04/2020<span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span>15:39</time></span></div>\n" +
            "<div class=\"cb-excerpt\">5 Mart'tan beri her Salı ve Cuma günleri e-posta kutularınıza gönderdiğimiz Covid-19 Postası bülteni, ilk bölümüyle artık YouTube kanalımızda da yayında. </div>\n" +
            "<div class=\"cb-post-meta\"><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/video/\" title=\"Video tarafından eklenmiş tüm yazılar\">Video</a></span><span class=\"cb-comments cb-element\"><a href=\"https://teyit.org/video-covid-19-postasi-1-bolum/#comments\">1 Yorum</a></span></div>\n" +
            "</div>\n" +
            "</article>\n" +
            "<article id=\"post-35018\" class=\"cb-blog-style-b cb-bs-c cb-module-a cb-article cb-article-row-3 cb-article-row cb-img-above-meta clearfix cb-separated cb-no-3 post-35018 post type-post status-publish format-standard has-post-thumbnail hentry category-analiz category-cevre category-yanlis category-yasam tag-bodrum tag-domuz tag-yaliciftlik\">\n" +
            "<div class=\"cb-mask cb-img-fw\" style=\"background-color: #222;\">\n" +
            "<a href=\"https://teyit.org/videonun-bodrumdaki-yaban-domuzlarini-gosterdigi-iddiasi/\"><img width=\"360\" height=\"240\" src=\"https://teyit.fra1.cdn.digitaloceanspaces.com/wp-content/uploads/2020/04/videonun-bodrumdaki-yaban-domuzlarini-gosterdigi-iddiasi-360x240.jpg\" class=\"attachment-cb-360-240 size-cb-360-240 wp-post-image\" alt=\"\" /></a> </div>\n" +
            "<div class=\"cb-meta\">\n" +
            "<h2 class=\"cb-post-title\"><a href=\"https://teyit.org/videonun-bodrumdaki-yaban-domuzlarini-gosterdigi-iddiasi/\">Videonun Bodrum&#8217;daki yaban domuzlarını gösterdiği iddiası</a></h2>\n" +
            "<div class=\"cb-byline\"><span class=\"cb-author\"> <a href=\"https://teyit.org/author/aliosman/\">Ali Osman Arabacı</a></span><span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span><span class=\"cb-date test\"><time datetime=\"2020-04-03\">03/04/2020<span class=\"cb-separator\"><i class=\"fa fa-times\"></i></span>16:38</time></span></div>\n" +
            "<div class=\"cb-excerpt\">Senarist Birol Güven tarafından 3 Nisan 2020’de Twitter’dan paylaşılan bir videonun, Bodrum Yalıçiftlik’teki yaban domuzlarını gösterdiği iddia edildi. Ancak iddia doğru değil.</div>\n" +
            "<div class=\"cb-post-meta\"><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/analiz/\" title=\"Analiz tarafından eklenmiş tüm yazılar\">Analiz</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/cevre/\" title=\"Çevre tarafından eklenmiş tüm yazılar\">Çevre</a></span><span class=\"cb-category cb-element\"><a href=\"https://teyit.org/konu/yasam/\" title=\"Yaşam tarafından eklenmiş tüm yazılar\">Yaşam</a></span><span class=\"cb-comments cb-element\"><a href=\"https://teyit.org/videonun-bodrumdaki-yaban-domuzlarini-gosterdigi-iddiasi/#comments\">2 yorum</a></span></div>\n" +
            "</div>";

}
